[package]
name = "lrxed"
build = "build.rs"
version = "0.2.0"
edition = "2024"
authors = ["Luna Present <code@lunapresent.net>", "Luna Heyman <luna.heyman@proton.me>"]
description = "A tui application for synchronising lyrics"
license = "EUPL-1.2"
repository = "https://github.com/LunaPresent/lrxed"
keywords = ["music", "lyrics", "synced-lyrics"]
categories = ["multimedia::audio"]

[dependencies]
oprabeli.path = "./oprabeli"
clap = { version = "4.5.49", features = [
	"derive",
	"cargo",
	"wrap_help",
	"unicode",
	"string",
	"unstable-styles",
] }
color-eyre = "0.6.5"
config = "0.15.18"
derive_more = { version = "2.0.1", features = ["deref", "display"] }
directories = "6.0.0"
edit = "0.1.5"
lofty = "0.22.4"
notify = "8.2.0"
rodio = "0.21.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_with = { version = "3.15.0", features = ["chrono"] }
strum = { version = "0.27.2", features = ["derive"] }
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
unicode-width = { version = "0.2.0", default-features = false }

[build-dependencies]
anyhow = "1.0.100"
vergen-git2 = { version = "1.0.7", features = ["build", "cargo"] }
