[workspace]
allow_dirty = true # allow updating repositories with uncommitted changes
dependencies_update = false # update dependencies with `cargo update`
git_release_enable = true
publish_allow_dirty = true
publish_no_verify = false
repo_url = "https://github.com/LunaPresent/lrxed"
semver_check = false
changelog_update = true

[changelog]
header = "# Changelog"
body = "Body"
trim = true
protect_breaking_commits = true
sort_commits = "newest"
commit_parsers = [
    { message = "^feat(\(.*\))?: add", group = "Added" },
	{ message = "^feat", group = "Changed" },
    { message = "^feat(\(.*\))?: remove", group = "Removed" },
    { message = "^feat(\(.*\))?: delete", group = "Removed" },
    { message = "^fix", group = "Fixed" },
	{ message = "^refactor", skip = true },
	{ message = "^ci", skip = true },
	{ message = "^docs", skip = true },
	{ message = "^chore", skip = true },
]
