# main whitespace settings
hard_tabs = true
max_width = 100
newline_style = "Unix"

# spaces around tokens
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
type_punctuation_density = "Wide"

# imports and mods
imports_indent = "Block"
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# literals
hex_literal_case = "Lower"
format_strings = true

# functions
fn_args_layout = "Tall"
fn_params_layout = "Tall"

# control statements
control_brace_style = "AlwaysSameLine"
combine_control_expr = false

# other style options
brace_style = "SameLineWhere"
empty_item_single_line = true
indent_style = "Block"
inline_attribute_width = 0
match_arm_blocks = true
reorder_impl_items = true
trailing_comma = "Vertical"
trailing_semicolon = true
where_single_line = true
wrap_comments = true

# misc
unstable_features = true
