name: Release

permissions:
  contents: write

on:
  release:
    types: [published]

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10

defaults:
  run:
    shell: bash

jobs:
  upload-assets:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - target: aarch64-unknown-linux-gnu
          os: ubuntu-24.04-arm
        - target: aarch64-apple-darwin
          os: macos-latest
        - target: aarch64-pc-windows-msvc
          os: windows-latest
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-latest
        - target: x86_64-apple-darwin
          os: macos-latest
        - target: x86_64-pc-windows-msvc
          os: windows-latest
    timeout-minutes: 60
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libasound2-dev
      if: startsWith(matrix.os, 'ubuntu')
    - run: echo "RUSTFLAGS=${RUSTFLAGS} -C target-feature=+crt-static" >> "${GITHUB_ENV}"
      if: endsWith(matrix.target, 'windows-msvc')
    - name: Build and upload binary
      uses: taiki-e/upload-rust-binary-action@v1
      with:
        archive: $bin-$tag-$target
        bin: lrxed
        target: ${{ matrix.target }}
        tar: unix
        zip: windows
        token: ${{ secrets.GITHUB_TOKEN }}
        include: README.md,LICENCE
